### ISSUE TITLE
Example how to get to the scroll elements to change styling

### ISSUE THREAD

**Issue by Arjanno** [daybrush/infinite-viewer#29]
Hi, 
I'm got my react app in darkmode which makes the default color of the vertical/horizontal scroll elements hard to see.
I think there's a means to get to to them but have been unable to find a way to override the color. Could you show an example?

**Comment by daybrush** [comment]
@Arjanno 

sorry. It's hard to customize though. You can do this by editing the css part.

![image](https://user-images.githubusercontent.com/3433062/181053132-fd298ec8-d707-4680-8f57-ed11002ab7c8.png)
```css
.infinite-viewer-scroll-thumb {
    background: red!important;
}
```
